const assert=require('assert');const{chromium}=require('/vercel/sandbox/node_modules/playwright');const BASE=process.env.QA_BASE||'http://127.0.0.1:8876';
const OUT={landingDesktop:'/data/student_samed_landing_v16_desktop.png',landingMobile:'/data/student_samed_landing_v16_mobile.png',accountDesktop:'/data/student_samed_account_v16_desktop.png',accountMobile:'/data/student_samed_account_v16_mobile.png',dashboardDesktop:'/data/student_samed_dashboard_v16_desktop.png',dashboardMobile:'/data/student_samed_dashboard_v16_mobile.png'};
async function openHarness(page,file,component){await page.goto(`${BASE}/scripts/${file}`,{waitUntil:'networkidle'});await page.waitForFunction(()=>window.__componentReady===true);const frame=page.frames().find(f=>f.url().includes(component));assert(frame,component);await page.waitForTimeout(550);return frame}
async function stable(page,max){const el=page.locator('#component');const first=await el.evaluate(x=>Math.round(x.getBoundingClientRect().height));const before=await page.evaluate(()=>window.__heightEvents.length);await page.waitForTimeout(1000);const second=await el.evaluate(x=>Math.round(x.getBoundingClientRect().height));const after=await page.evaluate(()=>window.__heightEvents.length);assert.strictEqual(second,first,`height grew ${first}->${second}`);assert(second>600&&second<max,`height ${second}`);assert(after-before<=1,`events ${before}->${after}`);return{height:second,events:after}}
async function targetTop(page,frame,selector){const fr=await page.locator('#component').evaluate(x=>x.getBoundingClientRect().top);const tr=await frame.locator(selector).evaluate(x=>x.getBoundingClientRect().top);const sr=await page.locator('section[data-testid="stMain"]').evaluate(x=>x.getBoundingClientRect().top);return Math.round(fr+tr-sr)}
async function scrollTop(page){return page.locator('section[data-testid="stMain"]').evaluate(x=>Math.round(x.scrollTop))}
async function screenshotBody(frame,path){await frame.locator('body').screenshot({path})}
(async()=>{const browser=await chromium.launch({headless:true,executablePath:'/usr/local/bin/chromium',args:['--no-sandbox']});const errors=[];const watch=p=>{p.on('pageerror',e=>errors.push(e.message));p.on('console',m=>{if(m.type()==='error')errors.push(m.text())})};
// Landing desktop: real Streamlit-like parent scroller, header anchors, modal, account action.
const landing=await browser.newPage({viewport:{width:1440,height:920}});watch(landing);const lf=await openHarness(landing,'landing_component_harness_v16.html','/landing_component/index.html');assert((await lf.locator('body').innerText()).includes('جميع المواد ستتوفر قريبًا'));const landingStable=await stable(landing,9000);await lf.locator('.nav-links a[href="#paths"]').click();await landing.waitForTimeout(650);assert((await scrollTop(landing))>500);assert(Math.abs(await targetTop(landing,lf,'#paths'))<55,`landing paths top ${await targetTop(landing,lf,'#paths')}`);await landing.locator('section[data-testid="stMain"]').evaluate(x=>x.scrollTo({top:0,behavior:'auto'}));await landing.waitForTimeout(100);await lf.locator('#howWorksBtn').click();assert(await lf.locator('#howModal').isVisible());assert.strictEqual(await lf.locator('.how-step').count(),3);const modalText=await lf.locator('#howModal').innerText();for(const t of ['أنشئ حسابك','سطح المكتب','اللوحات','الهاتف','تأسيس','مراجعة الدرس','تمارين الكتاب'])assert(modalText.includes(t),t);const modalTop=await targetTop(landing,lf,'.how-dialog');assert(modalTop>=0&&modalTop<750,`modal top ${modalTop}`);await lf.locator('[data-close-how]').last().click();assert(!(await lf.locator('#howModal').isVisible()));await lf.locator('#accountBtn').click();await landing.waitForFunction(()=>window.__componentValues.some(v=>v&&v.action==='open_onboarding'));await screenshotBody(lf,OUT.landingDesktop);
// Landing mobile menu and anchor.
const landingM=await browser.newPage({viewport:{width:390,height:844}});watch(landingM);const lmf=await openHarness(landingM,'landing_component_harness_v16.html','/landing_component/index.html');await lmf.locator('#menu').click();assert(await lmf.locator('.nav-links').evaluate(x=>x.classList.contains('open')));await lmf.locator('.nav-links a[href="#faq"]').click();await landingM.waitForTimeout(650);assert((await scrollTop(landingM))>1200);await screenshotBody(lmf,OUT.landingMobile);
// Account desktop: consistent UX, password confirmation, no PIN/PWA jargon, save event.
const account=await browser.newPage({viewport:{width:1240,height:900}});watch(account);const af=await openHarness(account,'onboarding_component_harness_v16.html','/onboarding_component/index.html');const accountText=await af.locator('body').innerText();assert(accountText.includes('الرجوع إلى الرئيسية'));assert(accountText.includes('جميع المواد'));assert(accountText.includes('سطح المكتب'));assert(accountText.includes('اللوحات'));assert(accountText.includes('الهاتف'));assert(!accountText.includes('PIN'));assert(!accountText.includes('PWA'));const accountStable=await stable(account,1800);await screenshotBody(af,OUT.accountDesktop);await af.locator('#studentName').fill('منير');await af.locator('#password').fill('secret1');await af.locator('#confirmPassword').fill('secret2');await af.locator('#submitBtn').click();assert(await af.locator('#error').isVisible());assert((await af.locator('#error').innerText()).includes('غير متطابقين'));await af.locator('#confirmPassword').fill('secret1');await af.locator('#submitBtn').click();await account.waitForFunction(()=>window.__componentValues.some(v=>v&&v.action==='save_profile'));const saved=await account.evaluate(()=>window.__componentValues.find(v=>v&&v.action==='save_profile'));assert.strictEqual(saved.profile.name,'منير');assert.strictEqual(saved.profile.password,'secret1');assert.strictEqual(saved.profile.confirm,'secret1');
const accountM=await browser.newPage({viewport:{width:390,height:844}});watch(accountM);const amf=await openHarness(accountM,'onboarding_component_harness_v16.html','/onboarding_component/index.html');await amf.locator('#backHome').click();await accountM.waitForFunction(()=>window.__componentValues.some(v=>v&&v.action==='back_home'));await screenshotBody(amf,OUT.accountMobile);
// Dashboard links and footer.
const dash=await browser.newPage({viewport:{width:1440,height:920}});watch(dash);const df=await openHarness(dash,'dashboard_component_harness_v16.html','/dashboard_component/index.html');await df.waitForFunction(()=>document.querySelector('#heroPct')?.textContent==='30%');const dashboardStable=await stable(dash,2800);await df.locator('[data-scroll="#learningPath"]').first().click();await dash.waitForTimeout(650);assert((await scrollTop(dash))>250);assert(Math.abs(await targetTop(dash,df,'#learningPath'))<55,`dashboard path top ${await targetTop(dash,df,'#learningPath')}`);await df.locator('[data-scroll="#platformFooter"]').first().click();await dash.waitForTimeout(650);const footerTop=await targetTop(dash,df,'#platformFooter');assert(footerTop>=0&&footerTop<920,`footer top ${footerTop}`);const footerText=await df.locator('#platformFooter').innerText();for(const t of ['أونلاين','أوفلاين','سطح المكتب','اللوحات','الهاتف'])assert(footerText.includes(t),t);assert(!footerText.includes('ZIP'));await df.locator('#platformFooter [data-scroll="#modulesSection"]').click();await dash.waitForTimeout(650);assert(Math.abs(await targetTop(dash,df,'#modulesSection'))<55);await screenshotBody(df,OUT.dashboardDesktop);
const dashM=await browser.newPage({viewport:{width:390,height:844}});watch(dashM);const dmf=await openHarness(dashM,'dashboard_component_harness_v16.html','/dashboard_component/index.html');await dmf.waitForFunction(()=>document.querySelector('#heroPct')?.textContent==='30%');const dashboardMobileStable=await stable(dashM,4000);const overflow=await dashM.evaluate(()=>({w:innerWidth,d:document.documentElement.scrollWidth,b:document.body.scrollWidth}));assert(overflow.d<=overflow.w+1&&overflow.b<=overflow.w+1,JSON.stringify(overflow));await screenshotBody(dmf,OUT.dashboardMobile);
assert.strictEqual(errors.length,0,errors.join('\n'));await browser.close();console.log('UI_V16_NAVIGATION_ACCOUNT_BROWSER_QA_OK');console.log(JSON.stringify({OUT,landingStable,accountStable,dashboardStable,dashboardMobileStable}));})().catch(e=>{console.error(e.stack||e);process.exit(1)});
